create table topicos(
    id bigint generated by default as identity,
    titulo varchar(100) not null unique,
    mensagem text not null unique,
    data_criacao timestamp not null,
    status varchar(50) not null,
    autor_id bigint not null,
    curso_id bigint not null,
    primary key(id),
    constraint fk_topicos_autor_id foreign key(autor_id) references usuarios(id),
    constraint fk_topicos_curso_id foreign key(curso_id) references cursos(id)
);
