create table respostas(
    id bigint generated by default as identity,
    mensagem text not null,
    topico_id bigint not null,
    data_criacao timestamp not null,
    autor_id bigint not null,
    solucao boolean not null default false,
    primary key(id),
    constraint fk_respostas_topico_id foreign key(topico_id) references topicos(id),
    constraint fk_respostas_autor_id foreign key(autor_id) references usuarios(id)
);
